In [1]:
from google.colab import files
uploaded = files.upload()

Saving WA_Fn-UseC_-Telco-Customer-Churn.csv to WA_Fn-UseC_-Telco-Customer-Churn.csv


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [3]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv', index_col=[0])

In [4]:
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
customerID                                                                  
7590-VHVEG  Female              0     Yes         No       1           No   
5575-GNVDE    Male              0      No         No      34          Yes   
3668-QPYBK    Male              0      No         No       2          Yes   
7795-CFOCW    Male              0      No         No      45           No   
9237-HQITU  Female              0      No         No       2          Yes   

               MultipleLines InternetService OnlineSecurity OnlineBackup  \
customerID                                                                 
7590-VHVEG  No phone service             DSL             No          Yes   
5575-GNVDE                No             DSL            Yes           No   
3668-QPYBK                No             DSL            Yes          Yes   
7795-CFOCW  No phone service             DSL            Yes           No   
9237-HQITU                No     Fiber optic             No           No   

           DeviceProtection TechSupport StreamingTV StreamingMovies  \
customerID                                                            
7590-VHVEG               No          No          No              No   
5575-GNVDE              Yes          No          No              No   
3668-QPYBK               No          No          No              No   
7795-CFOCW              Yes         Yes          No              No   
9237-HQITU               No          No          No              No   

                  Contract PaperlessBilling              PaymentMethod  \
customerID                                                               
7590-VHVEG  Month-to-month              Yes           Electronic check   
5575-GNVDE        One year               No               Mailed check   
3668-QPYBK  Month-to-month              Yes               Mailed check   
7795-CFOCW        One year               No  Bank transfer (automatic)   
9237-HQITU  Month-to-month              Yes           Electronic check   

            MonthlyCharges TotalCharges Churn  
customerID                                     
7590-VHVEG           29.85        29.85    No  
5575-GNVDE           56.95       1889.5    No  
3668-QPYBK           53.85       108.15   Yes  
7795-CFOCW           42.30      1840.75    No  
9237-HQITU           70.70       151.65   Yes

In [5]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(22)

In [7]:
df.duplicated()

customerID
7590-VHVEG    False
5575-GNVDE    False
3668-QPYBK    False
7795-CFOCW    False
9237-HQITU    False
              ...  
6840-RESVB    False
2234-XADUH    False
4801-JZAZL    False
8361-LTMKD    False
3186-AJIEK    False
Length: 7043, dtype: bool

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7021 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7021 non-null   object 
 1   SeniorCitizen     7021 non-null   int64  
 2   Partner           7021 non-null   object 
 3   Dependents        7021 non-null   object 
 4   tenure            7021 non-null   int64  
 5   PhoneService      7021 non-null   object 
 6   MultipleLines     7021 non-null   object 
 7   InternetService   7021 non-null   object 
 8   OnlineSecurity    7021 non-null   object 
 9   OnlineBackup      7021 non-null   object 
 10  DeviceProtection  7021 non-null   object 
 11  TechSupport       7021 non-null   object 
 12  StreamingTV       7021 non-null   object 
 13  StreamingMovies   7021 non-null   object 
 14  Contract          7021 non-null   object 
 15  PaperlessBilling  7021 non-null   object 
 16  PaymentMethod     7021 non-null 

In [11]:
for col in df.columns:
    if df[col].dtype == 'object':
        print(df.value_counts(col))

gender
Male      3541
Female    3480
Name: count, dtype: int64
Partner
No     3619
Yes    3402
Name: count, dtype: int64
Dependents
No     4911
Yes    2110
Name: count, dtype: int64
PhoneService
Yes    6339
No      682
Name: count, dtype: int64
MultipleLines
No                  3368
Yes                 2971
No phone service     682
Name: count, dtype: int64
InternetService
Fiber optic    3090
DSL            2419
No             1512
Name: count, dtype: int64
OnlineSecurity
No                     3490
Yes                    2019
No internet service    1512
Name: count, dtype: int64
OnlineBackup
No                     3080
Yes                    2429
No internet service    1512
Name: count, dtype: int64
DeviceProtection
No                     3087
Yes                    2422
No internet service    1512
Name: count, dtype: int64
TechSupport
No                     3465
Yes                    2044
No internet service    1512
Name: count, dtype: int64
StreamingTV
No                     2802
Y

In [12]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].astype(int, errors='ignore')
display(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 7021 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7021 non-null   object 
 1   SeniorCitizen     7021 non-null   int64  
 2   Partner           7021 non-null   object 
 3   Dependents        7021 non-null   object 
 4   tenure            7021 non-null   int64  
 5   PhoneService      7021 non-null   object 
 6   MultipleLines     7021 non-null   object 
 7   InternetService   7021 non-null   object 
 8   OnlineSecurity    7021 non-null   object 
 9   OnlineBackup      7021 non-null   object 
 10  DeviceProtection  7021 non-null   object 
 11  TechSupport       7021 non-null   object 
 12  StreamingTV       7021 non-null   object 
 13  StreamingMovies   7021 non-null   object 
 14  Contract          7021 non-null   object 
 15  PaperlessBilling  7021 non-null   object 
 16  PaymentMethod     7021 non-null 

None

In [13]:
from sklearn.preprocessing import LabelEncoder

# Select object type columns excluding 'TotalCharges'
categorical_cols = df.select_dtypes(include='object').columns.tolist()
if 'TotalCharges' in categorical_cols:
    categorical_cols.remove('TotalCharges')
if 'Churn' in categorical_cols:
    categorical_cols.remove('Churn')

# Apply Label Encoding
label_encoders = {}
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    df[col] = label_encoders[col].fit_transform(df[col])

display(df.head())

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
customerID                                                                     
7590-VHVEG       0              0        1           0       1             0   
5575-GNVDE       1              0        0           0      34             1   
3668-QPYBK       1              0        0           0       2             1   
7795-CFOCW       1              0        0           0      45             0   
9237-HQITU       0              0        0           0       2             1   

            MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
customerID                                                                 
7590-VHVEG              1                0               0             2   
5575-GNVDE              0                0               2             0   
3668-QPYBK              0                0               2             2   
7795-CFOCW              1                0               2             0   
9237-HQITU              0                1               0             0   

            DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
customerID                                                                
7590-VHVEG                 0            0            0                0   
5575-GNVDE                 2            0            0                0   
3668-QPYBK                 0            0            0                0   
7795-CFOCW                 2            2            0                0   
9237-HQITU                 0            0            0                0   

            Contract  PaperlessBilling  PaymentMethod  MonthlyCharges  \
customerID                                                              
7590-VHVEG         0                 1              2           29.85   
5575-GNVDE         1                 0              3           56.95   
3668-QPYBK         0                 1              3           53.85   
7795-CFOCW         1                 0              0           42.30   
9237-HQITU         0                 1              2           70.70   

            TotalCharges Churn  
customerID                      
7590-VHVEG         29.85    No  
5575-GNVDE       1889.50    No  
3668-QPYBK        108.15   Yes  
7795-CFOCW       1840.75    No  
9237-HQITU        151.65   Yes

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7021 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7021 non-null   int64  
 1   SeniorCitizen     7021 non-null   int64  
 2   Partner           7021 non-null   int64  
 3   Dependents        7021 non-null   int64  
 4   tenure            7021 non-null   int64  
 5   PhoneService      7021 non-null   int64  
 6   MultipleLines     7021 non-null   int64  
 7   InternetService   7021 non-null   int64  
 8   OnlineSecurity    7021 non-null   int64  
 9   OnlineBackup      7021 non-null   int64  
 10  DeviceProtection  7021 non-null   int64  
 11  TechSupport       7021 non-null   int64  
 12  StreamingTV       7021 non-null   int64  
 13  StreamingMovies   7021 non-null   int64  
 14  Contract          7021 non-null   int64  
 15  PaperlessBilling  7021 non-null   int64  
 16  PaymentMethod     7021 non-null 

In [15]:
df['Churn'][df['Churn'] == "Yes"] = 1
df['Churn'][df['Churn'] == "No"] = 0
df['Churn'] = df['Churn'].astype(int)

In [16]:
df.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
customerID                                                                     
7590-VHVEG       0              0        1           0       1             0   
5575-GNVDE       1              0        0           0      34             1   
3668-QPYBK       1              0        0           0       2             1   
7795-CFOCW       1              0        0           0      45             0   
9237-HQITU       0              0        0           0       2             1   

            MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
customerID                                                                 
7590-VHVEG              1                0               0             2   
5575-GNVDE              0                0               2             0   
3668-QPYBK              0                0               2             2   
7795-CFOCW              1                0               2             0   
9237-HQITU              0                1               0             0   

            DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
customerID                                                                
7590-VHVEG                 0            0            0                0   
5575-GNVDE                 2            0            0                0   
3668-QPYBK                 0            0            0                0   
7795-CFOCW                 2            2            0                0   
9237-HQITU                 0            0            0                0   

            Contract  PaperlessBilling  PaymentMethod  MonthlyCharges  \
customerID                                                              
7590-VHVEG         0                 1              2           29.85   
5575-GNVDE         1                 0              3           56.95   
3668-QPYBK         0                 1              3           53.85   
7795-CFOCW         1                 0              0           42.30   
9237-HQITU         0                 1              2           70.70   

            TotalCharges  Churn  
customerID                       
7590-VHVEG         29.85      0  
5575-GNVDE       1889.50      0  
3668-QPYBK        108.15      1  
7795-CFOCW       1840.75      0  
9237-HQITU        151.65      1

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7021 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7021 non-null   int64  
 1   SeniorCitizen     7021 non-null   int64  
 2   Partner           7021 non-null   int64  
 3   Dependents        7021 non-null   int64  
 4   tenure            7021 non-null   int64  
 5   PhoneService      7021 non-null   int64  
 6   MultipleLines     7021 non-null   int64  
 7   InternetService   7021 non-null   int64  
 8   OnlineSecurity    7021 non-null   int64  
 9   OnlineBackup      7021 non-null   int64  
 10  DeviceProtection  7021 non-null   int64  
 11  TechSupport       7021 non-null   int64  
 12  StreamingTV       7021 non-null   int64  
 13  StreamingMovies   7021 non-null   int64  
 14  Contract          7021 non-null   int64  
 15  PaperlessBilling  7021 non-null   int64  
 16  PaymentMethod     7021 non-null 

In [18]:
X = df.drop('Churn', axis=1)
y = df['Churn']

In [19]:
from sklearn.impute import SimpleImputer
import numpy as np

# Impute missing values in 'TotalCharges' using the mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X['TotalCharges'] = imputer.fit_transform(X[['TotalCharges']])

In [20]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.3, random_state=42)

In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

Model1 = DecisionTreeClassifier()
Model1.fit(X_train, y_train)
y_pred = Model1.predict(X_test)

Accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {Accuracy}")

Confusion_Matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(Confusion_Matrix)

Classification_Report = classification_report(y_test, y_pred)
print("Classification Report:")
print(Classification_Report)

Accuracy: 0.7950951919974185
Confusion Matrix:
[[1232  316]
 [ 319 1232]]
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.80      0.80      1548
           1       0.80      0.79      0.80      1551

    accuracy                           0.80      3099
   macro avg       0.80      0.80      0.80      3099
weighted avg       0.80      0.80      0.80      3099



In [32]:
from sklearn.ensemble import RandomForestClassifier

Model2 = RandomForestClassifier()
Model2.fit(X_train, y_train)
y_pred = Model2.predict(X_test)

Accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {Accuracy}")

Confusion_Matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(Confusion_Matrix)

Classification_Report = classification_report(y_test, y_pred)
print("Classification Report:")
print(Classification_Report)

Accuracy: 0.8415617941271378
Confusion Matrix:
[[1302  246]
 [ 245 1306]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.84      0.84      1548
           1       0.84      0.84      0.84      1551

    accuracy                           0.84      3099
   macro avg       0.84      0.84      0.84      3099
weighted avg       0.84      0.84      0.84      3099



In [33]:
from sklearn.linear_model import LogisticRegression

Model3 = LogisticRegression()
Model3.fit(X_train, y_train)
y_pred = Model3.predict(X_test)

Accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {Accuracy}")

Confusion_Matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(Confusion_Matrix)

Classification_Report = classification_report(y_test, y_pred)
print("Classification Report:")
print(Classification_Report)

Accuracy: 0.7960632462084544
Confusion Matrix:
[[1179  369]
 [ 263 1288]]
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.76      0.79      1548
           1       0.78      0.83      0.80      1551

    accuracy                           0.80      3099
   macro avg       0.80      0.80      0.80      3099
weighted avg       0.80      0.80      0.80      3099



In [25]:
from xgboost import XGBClassifier

# Initialize and train the XGBoost classifier
Model4 = XGBClassifier()
Model4.fit(X_train, y_train)

# Make predictions on the test set
y_pred = Model4.predict(X_test)

# Evaluate the model
Accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {Accuracy}")

Confusion_Matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(Confusion_Matrix)

Classification_Report = classification_report(y_test, y_pred)
print("Classification Report:")
print(Classification_Report)

Accuracy: 0.8380122620200064
Confusion Matrix:
[[1281  267]
 [ 235 1316]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.83      0.84      1548
           1       0.83      0.85      0.84      1551

    accuracy                           0.84      3099
   macro avg       0.84      0.84      0.84      3099
weighted avg       0.84      0.84      0.84      3099

